sudo: false
language: node_js
notifications:
  email: false
os:
  - osx
node_js:
  - '12'
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run coveralls
  - git clone --recursive https://github.com/dalisoft/nanoexpress.git
  - git checkout pro
  - npm run build
  - cp build/*.js .
  - git status
  - git pull origin pro-cjs-dist
  - git commit -a -m "[TravisCI] Updated Pro Distribute files" --allow-empty
  - git push "https://dalisoft:$SECRET@github.com/dalisoft/nanoexpress" pro-cjs-dist
