sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
os:
  - linux
  - osx
node_js:
  - '10'
  - '11'
  - '12'
install:
  - npm ci
script:
  - npm run lint
  - npm test
  - npm run coveralls
