language: node_js
notifications:
  email: false
os:
  - linux
  - osx
node_js:
  - '12'
  - '13'
  - '14'
install:
  - npm install
script:
  - npm run lint:analysis
  - npm test
#  - npm run coveralls
