sudo: false
language: node_js
notifications:
  email: false
os:
  - linux
  - osx
node_js:
  - '10'
  - '11'
  - '12'
before_install:
  - npm install -g greenkeeper-lockfile
install:
  - npm i cookie ajv fast-json-stringify
  - npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npm run lint
  - npm test
  - npm run coveralls
