sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
install:
  - npm i --prod
script:
  - npm run lint
  - npm test
  - npm run coveralls
